dist: trusty
cache: npm
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
  - npm test
sudo: required
before_deploy:
  - npm run build
  - source cico_release.sh
deploy:
  provider: script
  script: release
  on:
    branch: master
env:
  global:
  - secure: QrHxnE4x3et8t8+bSQBJ/ZmRYZbp8029ziee6av1ohybDilhAke+9IYkbdMJbhW8kvdlTjQ/t87TIsacDsvuXnFZXBLqNgJUcPAGBXNuO1792w16UQLCAZ/BpY2Q322SrufP/AIJgmL9zcTwpQ8RSuk4DL8yHg8zByJ2g5DXwcj4vwsyRmmgL4ERoRebsKYVznqB+3DhN5iuQlHaVOdgLOo74/MmxS6DWJCphvqnmyv4AqGRf9K/AAHeNbHAhYAymeDfUs1/8Sg9zgzFP9pdZlsYGmATBaXAtfH6hbfKGRQJ1Qq60CQ01yYTidCu7tFAJf10kXdUAWexU3oUQ0/4dAyKZnoV97MaK8qMbQWkxjnXZSMcxo/u2d2Ac34MW3SV3iQqGe9fwlSy8IV5ZvlYAUE4AlicVdihjAshtjWiBKqEot6UkequeaBSw4i8OXtxbi0tEdEKraFjIApgGfj1X1h/2RgjNoEQrFcKnvtjkUzNjSGysSTA/VvDcC2zcBVfeZt1QQcRqOGpBC5MxfQF77/sdOObrXP13QFWW48Cef2dOzmBGuiQzY3RAYzoL4ABpw0e1Qm40MjRLpdsXO7og/FdQnZCE98WNBvi3AutASId/qgQpakgL+Otb8fxhVJULIj7xlibZJzMRuThxo2f3jsMI+Q0KU95jlmo8GgzAW8=
  - secure: Q5pm67af93IYIZNoFgQYsvsLvkzWoQz+eQRLLYDWAPAVeEM3pCHhzWNugIMrbDGcTEOamhvr61wfLBZiB9uqYNGcsTcossi1OgcXOk5pXFIqCdtE8Ls2meY1he4VAwIYtnqRkTuw91p3863DAK5w3aaNv4Pqkoa5IAFR0TonoOpvkmIha+A1Ru0DX2hWHq4XxgZcD2UZ9AenOF46FkByBiHvF4/k8NLcKoUhq+oPyGhNErjUhB2SQ7Q5hF5LNLGyInS0++XSwDNWM7UN1AG5LYF9GKOSIMR64263MwVMoXmiq4DDX1eMAW4NZPk0J+vT40cRJUsW0/roIxSTvq39Ros1QuFMFQYJJOFYWhgCY1OOCXJ9cTdpykdtjuxU2SrJ9fFEFiuTG/0Om575njWZ8ydZ7dZT9PhqxY6fYfrCVn5O1ynf3w+i3ZAbJR8CjEuVllqXZZnO5JtsxHomqS/aLzRriaoOwfXQ2vkXnAW3O1IIRSkg/+hkUUwMgwApxeqg0iu/JRc2q8ozumPET1sMCY6QCQ67JnZ2DPIdZikz6BB8OPicYFdx99XRIR0rcar3aplONp2VD1zZ02lXg5YANA8Z1nNFYVsc43asgtKN62geLZXCUlaeLl+HbxmQk8xAhekstPOMoBvI6U1RkMTY8PZ1YxWCfQhA1Pv2/KoVvyY=
